spring.application.name=GoodreadsPlus-1
spring.datasource.url=jdbc:postgresql://localhost:5432/goodreadsplus
spring.datasource.username=postgres
spring.datasource.password=Pabloyalba1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true